# Generated by Django 3.2.7 on 2022-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_published',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
