# Generated by Django 3.2.7 on 2022-04-13 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_article_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('publish', 'Publish'), ('view', 'View'), ('edit', 'Edit'), ('comment', 'Comment')], max_length=10)),
                ('satoshi_amount', models.IntegerField()),
                ('r_hash', models.CharField(max_length=64)),
                ('payment_request', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending_invoice', 'Pending Invoice'), ('pending_payment', 'Pending Payment'), ('complete', 'Complete'), ('error', 'Error')], default='pending_invoice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='blog.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
