# Generated by Django 3.2.7 on 2022-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.AddField(
            model_name='payment',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
