# Generated by Django 3.2.7 on 2022-04-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='public email')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='location')),
                ('url', models.CharField(blank=True, max_length=50, verbose_name='url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'auth_profile',
            },
        ),
    ]
